# Generated by Django 4.0.2 on 2022-02-16 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='events',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='users',
            new_name='user',
        ),
    ]
