# Generated by Django 4.0.2 on 2022-02-17 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_photorecipe_photoprofile_photogroup_photoevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
